export const API_ENDPOINTS = {
  LOGIN: '/auth/login',
  REGISTER: '/auth/register',
  CONFIRM_VERIFICATION_CODE: '/auth/confirm-email-verification-code',
  FORGOT_PASSWORD: '/auth/forgot-password',
  RESET_PASSWORD: '/auth/reset-password',
  USERS: '/users',
  USER_PROFILE: '/user-profile',
  TIKTOK_AUTHORIZE: '/tiktok/auth/api/authorize',
  TIKTOK_EXCHANGE_CODE: '/tiktok/auth/api/exchange-code',
  TIKTOK_HANDLE_ACCESS_TOKEN: '/tiktok/auth/api/handle-access-token',
  TIKTOK_CONNECT_ACCOUNT: '/tiktok/auth/api/connect-tiktok-account',
  TIKTOK_USER_INFO: '/tiktok/auth/api/user-info',
  YOUTUBE_AUTHORIZE: '/youtube/auth/api/authorize',
  YOUTUBE_EXCHANGE_CODE: '/youtube/auth/api/exchange-code',
  YOUTUBE_HANDLE_ACCESS_TOKEN: '/youtube/auth/api/handle-access-token',
  YOUTUBE_CONNECT_ACCOUNT: '/youtube/auth/api/connect-youtube-account',
  YOUTUBE_FETCH_ANALYTICS: '/youtube/auth/api/fetch-analytics',
};
