export const INDUSTRIES = [
  'Lifestyle',
  'Fashion',
  'Beauty',
  'Travel',
  'Health & Fitness',
  'Food & Drink',
  'Comedy & Entertainment',
  'Family & Children',
  'Model',
  'Art & Photography',
  'Music & Dance',
  'Animals & Pets',
  'Adventure & Outdoors',
  'Education',
  'Entrepreneur & Business',
  'Athlete & Sports',
  'LGBTQ2+',
  'Gaming',
  'Vegan',
  'Technology',
  'Actor',
  'Healthcare',
  'Skilled Trades',
  'Automotive',
  'Cannabis',
  'Celebrity & Public Figure',
];
