export const INDUSTRIES = [
  { id: 1, name: 'Adventure & Outdoors' },
  { id: 2, name: 'Animals & Pets' },
  { id: 3, name: 'Art & Photography' },
  { id: 4, name: 'Athlete & Sports' },
  { id: 5, name: 'Automotive' },
  { id: 6, name: 'Beauty' },
  { id: 7, name: 'Cannabis' },
  { id: 8, name: 'Celebrity & Public Figure' },
  { id: 9, name: 'Comedy & Entertainment' },
  { id: 10, name: 'Education' },
  { id: 11, name: 'Entrepreneur & Business' },
  { id: 12, name: 'Family & Children' },
  { id: 13, name: 'Fashion' },
  { id: 14, name: 'Food & Drink' },
  { id: 15, name: 'Gaming' },
  { id: 16, name: 'Health & Fitness' },
  { id: 17, name: 'Healthcare' },
  { id: 18, name: 'LGBTQ2+' },
  { id: 19, name: 'Lifestyle' },
  { id: 20, name: 'Model' },
  { id: 21, name: 'Music & Dance' },
  { id: 22, name: 'Skilled Trades' },
  { id: 23, name: 'Technology' },
  { id: 24, name: 'Travel' },
  { id: 25, name: 'Vegan' },
];
